### ISSUE TITLE
Add ability to give/receive diff between panes

### ISSUE THREAD

**Issue by mertzt89** [mupchrch/split-diff#14]
I think it would be a good feature to be able to move diff'd hunks between panes. i.e. when performing a diff i would like to be able to to make the hunk in the right pane the same as the left (removing the difference) or vice versa.

**Comment by mupchrch** [comment]
I am still trying to think of what the user interaction would be. Anyone have any input? Sorry this is taking so long.

**Comment by pistou** [comment]
I'd see 2 arrows (right to left, left to right) in the gutter between the 2 files.
When you click on the arrow, it replaces the "old text" (xhat makes the diff) by the "new one".

**Comment by iDev0urer** [comment]
@mupchrch Just add a context menu item that says either "Copy to Right" or "Copy to Left" based on which side you do the right click on. I've used WinMerge, and although the user interface is horrible they have some pretty good options

**Comment by mupchrch** [comment]
1. So my initial thought was to only add context menu items when the user right clicks in a highlighted diff chunk. The Atom menu API does not support changing menu items based on marker highlights (they are in a private area of the DOM, so they can't be accessed to customize right click menus). Plus, I would still need to figure out which line the right click occurred over.

2. So then I tried adding context menu items based on the side that the right click occurs on. The version of coffeescript Atom uses does not allow dynamic object keys so I can't easily customize the menu per pane. A possible solution is to add a class to the DOM to identify to the menu builder which editor is which.

3. I have not tried adding anything to the gutters yet, so I may try that next.

In order to close out this issue, I would like to have at least number 1 implemented. But number 3 would be nice.

**Comment by iDev0urer** [comment]
When should we expect this to be implemented?

**Comment by mupchrch** [comment]
@iDev0urer Check for an update :wink:

For now the command moves any chunks that contain a cursor (it works with multiple cursors).

**Comment by mupchrch** [comment]
I am closing this due to the addition of the new footer bar UI, which has buttons for the `split-diff:copy-to-right` and `split-diff:copy-to-left` commands.
