### ISSUE TITLE
Right panel empty

### ISSUE THREAD

**Issue by michaelw85** [mupchrch/split-diff#16]
When I make a change (remove a couple of lines for example), save and then toggle split diff. The left shows everything red as removed and the right panel just shows an empty file and 1 empty line.

**Comment by mupchrch** [comment]
Yes, this package opens a new panel if there isn't two open so that you can paste the text you want to diff your original file with.

If there are already two panels open, it will diff the two panels. So if you have two files you want to diff, you would open them side by side and then toggle this package.

Let me know if you need any further clarification.

**Comment by michaelw85** [comment]
Wow, sorry for creating this "issue" for some reason I thought this would show my difference based on git, so last committed version compared to the what you are currently doing.

**Comment by mupchrch** [comment]
Definitely not a problem! I am hoping too add ability to diff with last committed at some point. ( #8 )

For now, https://atom.io/packages/git-time-machine might fulfill your need.
