### ISSUE TITLE
Close Pane and untitled file on toggle 

### ISSUE THREAD

**Issue by markediez** [mupchrch/split-diff#30]
At some point, it simply gets annoying to close the untitled file (asks if I want to save changes) when I'm done diffing.

**Comment by mupchrch** [comment]
Do you think `toggle` should auto close the untitled tile, or do you just not want it to prompt you to save?

**Comment by cliffordfajardo** [comment]
Personally, I don't mind the prompt. I'm not familiar with Atom's API for plugin development, but if there was an option in the settings like a checkbox

- [x] on diff tab close, show confirm dialog box

**Comment by mupchrch** [comment]
I am thinking about having it not prompt you to save if the editor was opened by split-diff `toggle`. If the user manually opened the editor, then it would still prompt as it does now.

@cliffordfajardo That would be straightforward, but I am afraid of adding too many settings so that the settings list becomes unnecessarily bloated.

**Comment by markediez** [comment]
@mupchrch Sorry for the late reply but yes. Essentially that plus closing the pane it created. 

Just to clarify this is the suggestion:

split-diff:Toggle -> Open new pane with the diff
split-diff:Toggle -> Close diff and pane without prompting to save

**Comment by mupchrch** [comment]
Toggle will close panes that were opened by split-diff. Manually closing the tab will still prompt the user.
