### ISSUE TITLE
New pane should open with same line ending (same files are shown as different)

### ISSUE THREAD

**Issue by thykka** [mupchrch/split-diff#39]
I recently started using split-diff in atom and there's a problem which raises it's head too often to ignore;
If I select an entire text file, copy it, then open split-diff and paste the contents to the right pane, sometimes it shows the right pane to be almost entirely different from the left ([screenshot](http://i.imgur.com/uyFaDrI.png)). Also, the left pane is suspiciously green...

How can this even happen?

**Comment by thykka** [comment]
Ok, so I noticed the diff pane opens in LF mode instead of CRLF. Once I switch that to match the other file, split-diff returns to normal operation.

**Comment by pistou** [comment]
You figured it out by yourself :+1: 

**CRLF** adds `\r\n` at the end of each line while **LF** adds `\n` 
Those are not visible from us, but `split-diff` catch them *I guess* ; which makes the difference.

**Comment by thykka** [comment]
Yeah, perhaps it would make sense for split-diff to open in the same line ending mode as the document it is opened for?

I don't see how the opposite would be useful in any scenario.

**Comment by pistou** [comment]
:+1: +1

**Comment by mupchrch** [comment]
Yes I agree, it should use the same line endings.

It's strange that even with "whitespace ignored", it still thinks the lines are different. I guess line endings don't count as whitespace!

**Comment by mupchrch** [comment]
Just as a follow up to this issue, it seems there is no information that atom keeps track of regarding line endings for an editor. The packages that know about what line ending an editor uses actually parse each line and assume the line ending that shows up the most is the one the editor is using. So I would have to do the same approach. That's why it is taking a little longer to get around to this!

**Comment by mupchrch** [comment]
Just to clarify, git repositories will _not_ have their line endings changed automatically. Line endings are only changed when a pane is auto opened by the package and is not a git repository.

**Comment by IceOnFire** [comment]
Hi,

I'm sorry but I still seem to have this issue on version 1.0.0. Would it be possible to set the new editor's line ending by retrieving the preferences set in the `line-ending-selector` package, which is installed by default in Atom?

Antony

**Comment by mupchrch** [comment]
@IceOnFire My solution uses some copied code from `line-ending-selector` package to calculate the line ending for the first editor and then sets the second editor's preferred line ending right before the user pastes.

What are the steps you are doing where you are seeing this not working? Are you having the package auto open the first/second pane for you? What OS are you on? Is the file you're trying to diff tracked by git? Does the file you're trying to diff have mixed line ending types (some lines end in `\n`, some end in `\r\n`)?

**Comment by IceOnFire** [comment]
Hi @mupchrch, thanks for the quick reply.

I'm running Atom 1.7.4 on Windows 10, `line-ending-selector` is configured to choose the OS default which is CRLF. My code is tracked by Git with the 'CRLF on local, LF on server' mode (`git config --global core.autocrlf true`).

The steps are the following:

1. I open a pane with my HTML (or JS, or whatever) code and see it is has CRLF line endings on the status bar.
2. I Ctrl-Shift-P search 'split diff' and select 'Split Diff: Toggle'.
3. A new pane opens along with a warning popup about line endings differing. The status bar states: LF UTF-8 HTML (synced with master, info provided by `git-plus`).
4. When I click on the original pane the status bar doesn't change, which is strange because it should tell me again it's a CRLF file. At first I assumed it was referring to the rightmost pane.
5. When I click on the newly created pane the status bar states: LF UTF-8 HTML, without Git info. So *now* the status bar is referring to the right pane.
6. Changing the line ending to LF on the first pane or to CRLF on the right pane solves the problem.

It seems like the line ending is misinterpeted by the system the very moment I try a split diff.

Please tell me if there's any other information I can provide.

Antony

**Comment by mupchrch** [comment]
Thanks for the awesomely detailed steps, that is really helpful!

So the way I implemented the feature is that if your file is part of a git repository, the `split-diff` package won't change any line endings. This is because I figured you'd want to know if your line endings differed before committing. I guess I didn't know that git could handle line endings like you've mentioned. So maybe I can simply change my code to not care about git repositories and your issue will be solved.

**Comment by IceOnFire** [comment]
That would be great, thank you! :smile:

**Comment by IceOnFire** [comment]
Thank you @mupchrch for the quick fix! There is still something missing though; I tried to solve it by myself in pull request https://github.com/mupchrch/split-diff/pull/61, let me know if it could work for you.

**Comment by IceOnFire** [comment]
Hi @mupchrch,

I just wanted to thank you for the fix, it works like a charm! And thank you for the amazing package!

Antony

**Comment by AlbertoFabbri93** [comment]
I have the same problem as described in first post. Maybe some updates to Atom broke this fix.
